### ISSUE TITLE
Comments shoul not be to-dos

### ISSUE THREAD

**Issue by marco-ih-bcn** [mathijs-and-jesse-second-project/mathijs-and-jesse#12]
https://github.com/Tablespoon-Travellers/Tablespoon-Travellers/blob/c54d723b504cd1a9ffa050a4f6671e3e5f985bd6/models/Recipe.model.js#L3

Move all to-dos into issues or into tasks.
Do not litter code with to-do comments

**Comment by JesseVermeulen123** [comment]
check!
